# Generated by Django 2.2.5 on 2019-10-24 05:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adventure', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('player_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='adventure.Player')),
            ],
            bases=('adventure.player',),
        ),
        migrations.CreateModel(
            name='Cyborg_Warrior',
            fields=[
                ('character_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='adventure.Character')),
            ],
            bases=('adventure.character',),
        ),
        migrations.CreateModel(
            name='Tech_Mage',
            fields=[
                ('character_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='adventure.Character')),
            ],
            bases=('adventure.character',),
        ),
    ]
