# Generated by Django 2.2.5 on 2019-10-25 03:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adventure', '0002_character_cyborg_warrior_tech_mage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cyborg_warrior',
            name='character_ptr',
        ),
        migrations.RemoveField(
            model_name='tech_mage',
            name='character_ptr',
        ),
        migrations.DeleteModel(
            name='Character',
        ),
        migrations.DeleteModel(
            name='Cyborg_Warrior',
        ),
        migrations.DeleteModel(
            name='Tech_Mage',
        ),
    ]
